/* eslint-disable prettier/prettier */
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FORGOTPASSWORDMAIL_STARTED = 'FORGOTPASSWORDMAIL_STARTED';
export const FORGOTPASSWORDMAIL_REQUEST = 'FORGOTPASSWORDMAIL_REQUEST';
export const FORGOTPASSWORDMAIL_SUCCESS = 'FORGOTPASSWORDMAIL_SUCCESS';
export const FORGOTPASSWORDMAIL_FAILURE = 'FORGOTPASSWORDMAIL_FAILURE';

export const CHANGE_PASSWORD_STARTED = 'CHANGE_PASSWORD_STARTED';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const SENT_OTP_STARTED = 'SENT_OTP_STARTED';
export const SENT_OTP_REQUEST = 'SENT_OTP_REQUEST';
export const SENT_OTP_SUCCESS = 'SENT_OTP_SUCCESS';
export const SENT_OTP_FAILURE = 'SENT_OTP_FAILURE';


export const SEARCH_BARCODE_STARTED = 'SEARCH_BARCODE_STARTED';
export const SEARCH_BARCODE_REQUEST = 'SEARCH_BARCODE_REQUEST';
export const SEARCH_BARCODE_SUCCESS = 'SEARCH_BARCODE_SUCCESS';
export const SEARCH_BARCODE_FAILURE = 'SEARCH_BARCODE_FAILURE';